name: Main Build
    
on:
  push:
    branches:
      - main

env:
  CI: true
  
jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout branch
      uses: actions/checkout@v4
    
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file
      
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v4
    - name: Create output with Gradle
      run: |
        pushd .build
        ./gradlew run --args="--asciidoc --config-file ../specification/good_practice.json"
        popd

    - name: Create artifacts folder and copy files
      run: ./.github/copy_artifacts.sh
      
    - name: Upload artifacts
      # if: success() && github.ref == 'refs/heads/main'
      uses: actions/upload-artifact@v4
      with:
        name: good_practice
        path: good_practice
